# Netlify configuration for Next.js (App Router) using Netlify Next.js Runtime
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/overview/

[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = [
    "data/products.json"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For static export, the Next.js Runtime plugin is not needed.

# Optional: set environment variables (can also be set in Netlify UI)
# [template.environment]
#   ADMIN_USERNAME = "admin"
#   ADMIN_PASSWORD = "admin1123"
